name: Publish Docker Image
on: push

# allow image publishing
permissions:
    contents: read
    packages: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        image: [ 'alpine', 'debian' ]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: confirm changes to ${{ matrix.image }}
        id: changes
        run: |
            if ! git diff --name-only origin/${{ github.event.repository.default_branch }}..HEAD | grep "^images/${{ matrix.image }}/"; then
                echo "No changes in images/${{ matrix.image }}, exiting early. . ."
                exit 0
            fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.image }} image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./images/${{ matrix.image }}/Dockerfile
          tags: ghcr.io/dlg1206/${{ matrix.image }}:latest
